#!/usr/bin/env python3
"""Extracts the expected values from Blockchain Commons' bc-ur test suite (tests/bc-ur-test.cpp) into a C header,
so the UR building blocks are checked against the reference implementation without transcribing numbers by hand."""
import re, sys

src = open(sys.argv[1]).read()


def body(fn):
    start = src.index(f"static void {fn}()")
    return src[start:src.index("\nstatic void", start + 1) if "\nstatic void" in src[start + 1:] else len(src)]


def ints(text, name):
    m = re.search(name + r"\s*=\s*\{([^;]*?)\};", text, re.S)
    return [int(x) for x in re.findall(r"-?\d+", m.group(1))]


def strings(text, name):
    m = re.search(name + r"\s*=\s*\{(.*?)\};", text, re.S)
    return re.findall(r'"([^"]*)"', m.group(1))


out = ["/* Generated by tools/gen_ur_ref_vectors.py from tests/bc-ur-test.cpp (Blockchain Commons bc-ur, BSD-2-Clause-Patent) */"]
def arr(ctype, name, values):
    out.append(f"static const {ctype} {name}[{len(values)}] = {{{', '.join(map(str, values))}}};")

arr("uint64_t", "REF_RNG_1", ints(body("test_rng_1"), "expected_numbers"))
arr("uint64_t", "REF_RNG_2", ints(body("test_rng_2"), "expected_numbers"))
arr("uint64_t", "REF_RNG_3", ints(body("test_rng_3"), "expected_numbers"))
arr("int", "REF_SAMPLER", ints(body("test_random_sampler"), "expected_samples"))
arr("int", "REF_SHUFFLE", ints(body("test_shuffle"), "expectedResult"))
arr("size_t", "REF_DEGREES", ints(body("test_choose_degree"), "expected_degrees"))
frag_sets = re.findall(r"\{([\d,\s]*)\}", re.search(r"expected_fragment_indexes\s*=\s*\{(.*?)\};", body("test_choose_fragments"), re.S).group(1))
flat = []
for s in frag_sets:
    v = [int(x) for x in re.findall(r"\d+", s)]
    flat += [len(v)] + v
arr("int", "REF_FRAGMENTS", flat)  # per seq_num 1..30: count, then sorted indexes
b2 = body("test_bytewords_2")
arr("uint8_t", "REF_BYTEWORDS_2_INPUT", ints(b2, "ByteVector input"))
minimal = "".join(re.findall(r'"([a-z]+)"', re.search(r"encoded_minimal\s*=(.*?);", b2, re.S).group(1)))
out.append(f'static const char REF_BYTEWORDS_2_MINIMAL[] = "{minimal}";')
out.append(f'static const char REF_SINGLE_PART[] = "{re.search(r"string expected = \"([^\"]+)\"", body("test_single_part_ur")).group(1)}";')
parts = strings(body("test_ur_encoder"), "expected_parts")
out.append("static const char *const REF_PARTS[] = {" + ", ".join(f'"{p}"' for p in parts) + "};")
open(sys.argv[2], "w").write("\n".join(out) + "\n")
print(f"parts={len(parts)} fragments_sets={len(frag_sets)}")
